### ISSUE TITLE
IPTV Manager support

### ISSUE THREAD

**Issue by Testato** [add-ons/plugin.video.redbulltv#27]
it not work or i don't understand how it work ?

I'm on Win10
Installed IPTV Manager script from official kodi repo
Installed you RedbullTV from official kodi repo
Rebooted Kodi.

I select TV on kodi menu but nothing appear

![1](https://user-images.githubusercontent.com/6893841/104212608-b31db300-5435-11eb-942a-401221ef3cf7.PNG)

![2](https://user-images.githubusercontent.com/6893841/104212644-b9ac2a80-5435-11eb-967e-ab22cf9dde34.PNG)

**Comment by michaelarnauts** [comment]
There is a Dutch guide here, maybe Google Translate can help, or the screenshots might be enough. You basically have to install IPTV Manager from the repo, go to it's settings, allow it to configure simple IPTV and do a refresh of the channels and guide data.

https://github.com/add-ons/service.iptv.manager/wiki/Installation-(NL)

**Comment by piejanssens** [comment]
Now also available in EN https://github.com/add-ons/service.iptv.manager/wiki/Installation

**Comment by Testato** [comment]
Thanks a lot for the information, now it work
I will copy your IPTV Manager integration for my plugins :-)
https://github.com/Testato/plugin.video.repubblicaitaliana
https://github.com/luivit/plugin.video.rivedila7
